#도커 연동 전.
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: budget_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 # config 설정을 끄기.
  cloud:
    config:
      enabled: false
# gateway 설정을 끄기.
    gateway:
      enabled: true
# eureka 설정
    discovery:
      enabled: true
  application:
    name: statis-service
# circuit-breaker 설정 끄기.
    circuitbreaker:
      enabled: false
#  sql:
#    init:
#      mode: always
# security 설정 끄기
#  security:
#    enabled: false
  logging:
    level:
      root: debug
      org.springframework: debug
jwt:
  secret: w9vM9r6ZKLEFh82N0UbpVYkRIuv2AfxN


