#도커 연동 전.
server:
  port: 8090
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/budget_test_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&allowMultiQueries=true
#    username: budget_test_statis
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
 # config 설정을 끄기.
  cloud:
    config:
      enabled: false
# gateway 설정을 끄기.
    gateway:
      enabled: false
# eureka 설정
    discovery:
      enabled: true
  application:
    name: statis-service_test
# circuit-breaker 설정 끄기.
    circuitbreaker:
      enabled: false
#  sql:
#    init:
#      mode: always
  logging:
    level:
      root: debug
      org.springframework: debug